=== Aman0971/BRIDGELABZ-JAVA-Training/Library_Management/src/main/resources/ transaction-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "TransactionList",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "transactionId": { "type": "string" },
      "patronName": { "type": "string", "minLength": 1 },
      "bookId": { "type": "integer", "minimum": 1 },
      "borrowDate": { "type": "string" },
      "dueDate": { "type": "string" },
      "status": { "type": "string" },
      "fine": { "type": "number", "minimum": 0 }
    },
    "required": ["transactionId", "patronName", "bookId", "borrowDate", "dueDate", "status", "fine"]
  }
}

=== Aman0971/BRIDGELABZ-JAVA-Training/Library_Management/src/main/resources/transactions.json
[
  {
    "transactionId": "TXN-1001",
    "patronName": "kiran",
    "bookId": 1001,
    "borrowDate": "2026-06-15",
    "dueDate": "2026-06-29",
    "status": "Borrowed",
    "fine": 0.0
  },
  {
    "transactionId": "TXN-1002",
    "patronName": "sohil",
    "bookId": 1003,
    "borrowDate": "2026-06-18",
    "dueDate": "2026-07-02",
    "status": "Borrowed",
    "fine": 0.0
  }
]
